### ISSUE TITLE
Creative Assignment 1 Ready for Grading!

### ISSUE THREAD

**Issue by mcasey24** [VIS-2129-F2020/mcasey-vis#1]
HTML: https://vis-2129-f2020.github.io/mcasey-vis/Creative1

**Comment by c-voulgaris** [comment]
This looks great! 

On plot 10 (the quantile plot) - the plots created by geom_quantile aren't terribly intuitive. I suggest adding some explanatory text (perhaps as annotation to the graph itself) explaining what the lines mean. You can read more about it here: https://ggplot2.tidyverse.org/reference/geom_quantile.html
